### ISSUE TITLE
Timeline for 0.3 changes? Help needed?

### ISSUE THREAD

**Issue by kirillsalykin** [specta-rs/rspc#299]
Hi there,

I'm really interested in rspc, but I’ve noticed that some of the documentation and examples seem to be a bit outdated or inconsistent. I would greatly appreciate any updates you can provide on the current plans and progress, including any timelines you might have.

As a Rust newcomer, I would also love to offer my assistance in any way I can. Looking forward to hearing from you!

**Comment by oscartbeaumont** [comment]
What we need before launching alpha:
 - [ ] Export Typescript types for the the legacy bindings format
 - [ ] `rspc_axum` websocket support (including legacy iterop)
 - [ ] `rspc_axum` batching support (including legacy iterop)
 - [ ] Handling invalid serde errors without panicking
 - [ ] Duplicate procedure name errors
 - [ ] Validate procedure names are URL safe and don't interfere with built-in stuff (`ws`, `_batch`, etc)
 - [ ] Properly handle panics in procedures
 - [ ] `procedure::Procedure*` can probs drop `Procedure` from the start of their name

Before final launch:
 - [ ] rspc should not publicly depend on `specta-util`
 - [ ] Finish the new Typescript client's (for the initial launch the old one will work fine due to the new stuff having backwards compatibility)
 - [ ] Rust doc cleanup + finish
 - [ ] Publish docs overhaul

This list is not fully inclusive but it contains the big things.

Another major blocker to the final launch is that rspc depends on pre-release versions of Specta although in relativity we can just do crates.io prereleases for rspc until Specta is ready to v2.

In terms of timeline, right now I don't actively use rspc in any of my own projects and am overall not really enjoying software development so I can't put a timeline on it as much as I want to.

rspc is in such a rough state right now but can't wait to hopefully one day be in a much better state once this new version launches!
